# Generated by Django 5.1.4 on 2025-01-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.URLField()),
                ('precio', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
