# Generated by Django 5.1.4 on 2025-01-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_url_articulo_enlace_articulo_calificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='enlace',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='vendedor',
        ),
    ]
