# Generated by Django 5.1.4 on 2025-01-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_enlace_articulo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
